### PR TITLE
Add caching to Youtube service

### LINKED ISSUE #83: Cache or handle YouTube rate limits
From the addition of YouTube into the live command from #70  

YouTube API limits suck, should be cached or another solution created.

image

### PR DESCRIPTION
**Pull request by dotted**
Fixes #83

### CODE REVIEW

**Comment by dotted** [comment]
A better solution would be to dump the playlist id and channel id in the DB, as I don't think they are prone to change though could be wrong.

**Comment by shadedred** [comment]
It's fine to keep it in memory, the bot is long running, and one additional call on startup to prevent dealing with state is fine.

**Comment by shadedred** [comment]
Also, adding a configurable cached  number of viewers from the API call is probably also a good move, as !live could be called several times, and having it update once every 5 or 10 minutes is absolutely alright, and will save on a ton of calls.

Just slap a timestamp into the API on viewer call, if less then the configurable duration has passed, just return the last value.

**Comment by dotted** [comment]
Not sure how to test this if quotas are exceeded, but I have tested this against Destiny's channels and it returns proper result for twitch and youtube

**Comment by shadedred** [comment]
Looks good, let's get it in!

**Pull request merged**
