### PR TITLE
Command for timed bans (!timebomb)

### PR DESCRIPTION
**Pull request by gabrieljablonski**
To be used on "link or ipban" situations, which happen quite often.

```
Destiny: has anyone figured out what happened to the doc?

Jabelonske: yes Destiny
> it was just a marketing stunt

Destiny: Jabelonske link source or ipban. you have 30 seconds
> !timebomb 1024h 30s Jabelonske
```

### CODE REVIEW

**Comment by shadedred** [comment]
Thanks for the contribution! 

Did you test this manually? Looks pretty good, gotta talk to cake and mods to ensure it's something we want, but we can probably get this in.

Probably a few tweaks like changing the name of the command.

**Comment by gabrieljablonski** [comment]
Yes, I tested it manually.

Following the theme for the nuke command, this was the first name that came to mind. 
But of course suggestions are open.

**Comment by shadedred** [comment]
@ILiedAboutCake what's the deal here let's not keep PRs open for a while, is this a no go, or a go?

**Comment by gabrieljablonski** [comment]
@ILiedAboutCake REVIEW MEEE OOOO

**Pull request closed without merging**
