### PR TITLE
Bump dependencies and node version

### LINKED ISSUE #64: Update packages.json to support Node 14
Production is currently running Node 10 and cannot be upgraded to 12+ without throwing package errors + node gyp compile errors.

`package.json`  should be bumped to the latest stable versions + any changed required to make the bot run under Node 14.

### PR DESCRIPTION
**Pull request by dotted**
This fixes #64 

- [x] Figure out why Cake can't build this on his setup

### CODE REVIEW

**Comment by dotted** [comment]
Twitch chat functionality is probably broken in this build

**Comment by dotted** [comment]
I'm not gonna bump `twitch-js` dependency, so the only thing left is figuring out why @ILiedAboutCake can't build this in Docker, unfortunately I haven't been able to reproduce it on my machine.

I also think Influx still works, the calls made to the HTTP interface does add the `pathPrefix` to the URL when I'm looking at the logs, but it breaks for me presumably because I don't have a proxy setup for InfluxDB and so it throws an error in the log on start.

**Comment by shadedred** [comment]
We'll do a bit o testin' for this before we merge it in. It'd be wild if the google APIs didn't break, many major version changes

**Comment by dotted** [comment]
Cake is working on getting this to build in Docker, so this PR is GTG.

**Pull request merged**
