### PR TITLE
Mute cap

### PR DESCRIPTION
**Pull request by tbreslein**
Regarding issue #60 .

Finally got around to put this together, sorry I announced that I would do this almost a week ago ^^'

Btw, in case there are other blind boomers around that might wanna contrib to this and didn't see the makefile, maybe it should be noted in the Readme :D Took me way longer than I like to admit fiddling around with just npm first, and then docker, only to see that finally.

### CODE REVIEW

**Comment by johnpyp** [comment]
Maybe a good idea to add a test for this, perhaps under `tests/lib/punishment-read-write-stream.js`. You'd just want to instantiate a new PunishmentReadWriteStream with a mock services object, and then listen to emitted `data` to verify the cap is enforced, in the style of https://github.com/destinygg/chat-bot/blob/master/lib/message-routing/chat-service-router.js#L114.

**Comment by shadedred** [comment]
I'm cool to merge either way, lemme know if you wanna try  tackling a test or not.

**Comment by tbreslein** [comment]
Yeah, I'm gonna try that. Good opportunity to learn how the testing framework works that you're using, though it looks like what I'm used to from Haskell's libraries, so that shouldn't be hard. Might pester people on discord if I end up being too stoopid.

**Comment by tbreslein** [comment]
Got around to adding the tests. The `TypeError` test might be redundant, since that type of error should be thrown when the initial input duration is parsed, but I figured that it probably won't hurt either.

**Pull request merged**
