### PR TITLE
!svoteban Implementation

### PR DESCRIPTION
**Pull request by johnpyp**
Using the new [/svote command in dgg](https://github.com/destinygg/chat-gui/pull/18) which weighs votes in a poll by subs, i.e a p2w model, this is an implementation of !voteban and !voteipban using this new paradigm and weighting system. The command interface for them is nearly identical, with minor modifications on text and how many votes to add based off sub status.

New commands:
- !svoteban
- !svoteipban

Weights:
- Tier 4: 16 votes
- Tier 3: 8 votes
- Tier 2: 4 votes
- Tier 1: 2 votes
- Twitch Sub: 2 votes
- Anything else: 1 vote

- [x] No tests
- [x] Not even tested manually
- [x] Probably doesn't work

Ready to ship! :rocket:

### CODE REVIEW

**Comment by coolcodehere** [comment]
great change!

**Comment by Gort218** [comment]
based change!

**Comment by coolcodehere** [comment]
Is it 1 vote to kick non-subs period? That seems like it could be easily abused.

**Comment by coolcodehere** [comment]
a

**Comment by shadedred** [comment]
It'd be nice if you factored out common functionality between the two vote bans.

**Pull request merged**
